import { GameMap, MapRoute, Transport } from "../models/types.ts";

const routes: MapRoute = {
  116: [
    { to: 117, mode: Transport.Taxi },
    { to: 128, mode: Transport.Taxi },
    { to: 127, mode: Transport.Taxi },
    { to: 118, mode: Transport.Bus },
    { to: 127, mode: Transport.Bus },
    { to: 128, mode: Transport.Bus },
  ],
  117: [
    { to: 116, mode: Transport.Taxi },
    { to: 118, mode: Transport.Taxi },
    { to: 129, mode: Transport.Taxi },
  ],
  118: [
    { to: 117, mode: Transport.Taxi },
    { to: 119, mode: Transport.Taxi },
    { to: 116, mode: Transport.Bus },
    { to: 135, mode: Transport.Bus },
  ],
  119: [
    { to: 118, mode: Transport.Taxi },
    { to: 136, mode: Transport.Taxi },
  ],
  127: [
    { to: 116, mode: Transport.Taxi },
    { to: 133, mode: Transport.Taxi },
    { to: 134, mode: Transport.Taxi },
    { to: 116, mode: Transport.Bus },
    { to: 133, mode: Transport.Bus },
  ],
  128: [
    { to: 116, mode: Transport.Taxi },
    { to: 129, mode: Transport.Taxi },
    { to: 134, mode: Transport.Taxi },
    { to: 142, mode: Transport.Taxi },
    { to: 116, mode: Transport.Bus },
    { to: 142, mode: Transport.Bus },
  ],
  129: [
    { to: 117, mode: Transport.Taxi },
    { to: 128, mode: Transport.Taxi },
    { to: 135, mode: Transport.Taxi },
    { to: 142, mode: Transport.Taxi },
    { to: 143, mode: Transport.Taxi },
  ],
  133: [
    { to: 127, mode: Transport.Taxi },
    { to: 140, mode: Transport.Taxi },
    { to: 141, mode: Transport.Taxi },
    { to: 127, mode: Transport.Bus },
    { to: 157, mode: Transport.Bus },
  ],
  134: [
    { to: 127, mode: Transport.Taxi },
    { to: 128, mode: Transport.Taxi },
    { to: 141, mode: Transport.Taxi },
    { to: 142, mode: Transport.Taxi },
  ],
  135: [
    { to: 129, mode: Transport.Taxi },
    { to: 136, mode: Transport.Taxi },
    { to: 143, mode: Transport.Taxi },
    { to: 161, mode: Transport.Taxi },
    { to: 118, mode: Transport.Bus },
    { to: 159, mode: Transport.Bus },
    { to: 161, mode: Transport.Bus },
  ],
  141: [
    { to: 133, mode: Transport.Taxi },
    { to: 134, mode: Transport.Taxi },
    { to: 142, mode: Transport.Taxi },
    { to: 158, mode: Transport.Taxi },
  ],
  136: [
    { to: 119, mode: Transport.Taxi },
    { to: 135, mode: Transport.Taxi },
    { to: 162, mode: Transport.Taxi },
  ],
  142: [
    { to: 128, mode: Transport.Taxi },
    { to: 129, mode: Transport.Taxi },
    { to: 134, mode: Transport.Taxi },
    { to: 141, mode: Transport.Taxi },
    { to: 143, mode: Transport.Taxi },
    { to: 158, mode: Transport.Taxi },
    { to: 159, mode: Transport.Taxi },
    { to: 128, mode: Transport.Bus },
    { to: 157, mode: Transport.Bus },
    { to: 159, mode: Transport.Bus },
  ],
  143: [
    { to: 129, mode: Transport.Taxi },
    { to: 135, mode: Transport.Taxi },
    { to: 142, mode: Transport.Taxi },
    { to: 159, mode: Transport.Taxi },
    { to: 160, mode: Transport.Taxi },
  ],
  157: [
    { to: 158, mode: Transport.Taxi },
    { to: 170, mode: Transport.Taxi },
    { to: 133, mode: Transport.Bus },
    { to: 142, mode: Transport.Bus },
    { to: 185, mode: Transport.Bus },
  ],
  158: [
    { to: 141, mode: Transport.Taxi },
    { to: 142, mode: Transport.Taxi },
    { to: 157, mode: Transport.Taxi },
    { to: 171, mode: Transport.Taxi },
  ],
  159: [
    { to: 142, mode: Transport.Taxi },
    { to: 143, mode: Transport.Taxi },
    { to: 160, mode: Transport.Taxi },
    { to: 172, mode: Transport.Taxi },
    { to: 188, mode: Transport.Taxi },
    { to: 142, mode: Transport.Bus },
    { to: 135, mode: Transport.Bus },
    { to: 161, mode: Transport.Bus },
    { to: 187, mode: Transport.Bus },
    { to: 199, mode: Transport.Bus },
    { to: 89, mode: Transport.Metro },
    { to: 185, mode: Transport.Metro },
  ],
  160: [
    { to: 143, mode: Transport.Taxi },
    { to: 159, mode: Transport.Taxi },
    { to: 161, mode: Transport.Taxi },
    { to: 173, mode: Transport.Taxi },
  ],
  161: [
    { to: 135, mode: Transport.Taxi },
    { to: 160, mode: Transport.Taxi },
    { to: 174, mode: Transport.Taxi },
    { to: 135, mode: Transport.Bus },
    { to: 159, mode: Transport.Bus },
    { to: 199, mode: Transport.Bus },
  ],
  162: [
    { to: 136, mode: Transport.Taxi },
    { to: 175, mode: Transport.Taxi },
  ],
  170: [
    { to: 157, mode: Transport.Taxi },
    { to: 171, mode: Transport.Taxi },
    { to: 185, mode: Transport.Taxi },
  ],
  171: [
    { to: 158, mode: Transport.Taxi },
    { to: 170, mode: Transport.Taxi },
    { to: 172, mode: Transport.Taxi },
    { to: 186, mode: Transport.Taxi },
    { to: 198, mode: Transport.Taxi },
  ],
  172: [
    { to: 159, mode: Transport.Taxi },
    { to: 171, mode: Transport.Taxi },
    { to: 187, mode: Transport.Taxi },
  ],
  173: [
    { to: 160, mode: Transport.Taxi },
    { to: 174, mode: Transport.Taxi },
    { to: 188, mode: Transport.Taxi },
    { to: 200, mode: Transport.Taxi },
  ],
  174: [
    { to: 161, mode: Transport.Taxi },
    { to: 173, mode: Transport.Taxi },
    { to: 175, mode: Transport.Taxi },
  ],
  175: [
    { to: 162, mode: Transport.Taxi },
    { to: 174, mode: Transport.Taxi },
    { to: 200, mode: Transport.Taxi },
  ],
  185: [
    { to: 170, mode: Transport.Taxi },
    { to: 186, mode: Transport.Taxi },
    { to: 157, mode: Transport.Bus },
    { to: 187, mode: Transport.Bus },
    { to: 159, mode: Transport.Metro },
  ],
  186: [
    { to: 171, mode: Transport.Taxi },
    { to: 185, mode: Transport.Taxi },
    { to: 198, mode: Transport.Taxi },
  ],
  187: [
    { to: 172, mode: Transport.Taxi },
    { to: 188, mode: Transport.Taxi },
    { to: 198, mode: Transport.Taxi },
    { to: 159, mode: Transport.Bus },
    { to: 185, mode: Transport.Bus },
  ],
  188: [
    { to: 159, mode: Transport.Taxi },
    { to: 173, mode: Transport.Taxi },
    { to: 187, mode: Transport.Taxi },
    { to: 199, mode: Transport.Taxi },
  ],
  198: [
    { to: 171, mode: Transport.Taxi },
    { to: 186, mode: Transport.Taxi },
    { to: 187, mode: Transport.Taxi },
    { to: 199, mode: Transport.Taxi },
  ],
  199: [
    { to: 188, mode: Transport.Taxi },
    { to: 198, mode: Transport.Taxi },
    { to: 200, mode: Transport.Taxi },
    { to: 159, mode: Transport.Bus },
    { to: 161, mode: Transport.Bus },
  ],
  200: [
    { to: 173, mode: Transport.Taxi },
    { to: 175, mode: Transport.Taxi },
    { to: 199, mode: Transport.Taxi },
  ],
};

export const basicMap: GameMap = {
  startingPositions: [118, 173, 187, 133, 128, 185, 198, 200],
  routes,
};
